networks:
  app-server:
    driver: bridge
  app-data:
    driver: bridge

services:
    backend:
      container_name: backend
      build: 
        context: ./backend
        dockerfile: Dockerfile
      ports:
        - "9000:9000"
      depends_on:
        - mysql
      networks:
        - app-data
        - app-server

    mysql:
      image : mysql:8.0
      container_name : mysql
      volumes:
        - ./mysql/data:/var/lib/mysql
        - ./start.sql:/docker-entrypoint-initdb.d/start.sql
      ports:
        - "3306:3306"
      environment:
        MYSQL_DATABASE: laravel
        MYSQL_ROOT_PASSWORD: secret
      networks:
        - app-data

    server:
      image: nginx:alpine
      container_name: server
      ports:
        - "8080:80"
      volumes:
        - ./nginx/backend/default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - backend
        - mysql
      networks:
        - app-server

    frontend:
      build: 
        context: ./frontend
        dockerfile: Dockerfile
      container_name: frontend
      ports:
        - "8000:80"
      volumes:
        - ./nginx/frontend/default.conf:/etc/nginx/conf.d/default.conf